name: FlickeringPumpkins
version: '${project.version}'
main: me.stephenminer.flickerpumpkins.FlickeringPumpkins
api-version: '1.20'
load: STARTUP
commands:
  give-pumpkin:
    aliases:
      - givepumpkin
      - gpumpkin
      - gp
    permission: "flickerpumpkins.commands.give"
  pumpkinreload:
    permission: "flickerpumpkins.commands.reload"
    aliases:
      - preload



